# -*- coding: utf-8 -*-
"""Grupo19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qcym_xxFt6y7-nVm636PVTMH_9dqBJaC
"""

import pandas as pd
import matplotlib.pyplot as plt

excel = "/content/drive/MyDrive/Base de Datos - Grupo 19.xlsx"
df = pd.read_excel(excel)
writer = pd.ExcelWriter(excel)

while True:
  print("Menú de opciones")
  print("1. Ingresar datos a la Base de Datos")
  print("2. Filtrar datos")
  print("3. Solicitar gráficos de análisis")
  print("4. Solicitar datos estadísticos")
  print("5. Crear nuevas columnas")
  print("6. Ver Base de Datos")
  print("7. Salir")

  op = int(input("Ingrese opción: "))

  if op == 1:
    datos = {}
    for columna in df.columns:
      valor = input("Ingrese {}: ".format(columna))
      if valor.isdigit():
        valor = float(valor)
      datos[columna] = valor
    df_dest = df.append(datos, ignore_index=True)
    df_dest.to_excel(writer, index=False)
    df = df_dest
    writer.save()
    print("Datos ingresados correctamente.")
  elif op == 2:
    print("1. Filtrar por valor menor a")
    print("2. Filtrar por valor mayor a")
    print("3. Filtrar por valor igual a")
    print("4. Filtrar por texto contiene a")
    op2 = int(input("Ingrese opción: "))
    columna = input("Ingrese nombre de la columna a filtrar: ")
    valor = input("Ingrese valor: ")
    if columna in df.columns:
      if op2 == 1:
        filtrado = df[df[columna] < float(valor)]
      elif op2 == 2:
        filtrado = df[df[columna] > float(valor)]
      elif op2 == 3:
        filtrado = df[df[columna] == float(valor)]
      elif op2 == 4:
        filtrado = df[df[columna].str.contains(valor)]
      print(filtrado.head())
    else:
      print("La columna ingresada no se encuentra.")
  elif op == 3:
    poblacion = df['POBLACION'].tolist()
    dosis = df['DOSIS'].tolist()
    plt.scatter(poblacion,dosis)
    plt.xlabel("Poblacion")
    plt.ylabel("Dosis")
    plt.show()
  elif op == 4:
    print("1. Valor promedio")
    print("2. Valor más bajo")
    print("3. Valor más alto")
    op4 = int(input("Ingrese opción: "))
    columna = input("Ingrese nombre de la columna a calcular: ")
    if columna in df.columns:
      if op4 == 1:
        promedio = df[columna].mean()
        print("El promedio de {} es: {}".format(columna,promedio))
      elif op4 == 2:
        min = df[columna].min()
        print("El valor mas bajo de {} es: {}".format(columna,min))
      elif op4 == 3:
        max = df[columna].max()
        print("El valor mas alto de {} es: {}".format(columna,max))
    else:
      print("La columna ingresada no se encuentra.")
  elif op == 5:
    columna = input("Ingrese nombre de la columna a crear: ")
    if columna not in df.columns:
      df[columna] = ""
      df.to_excel(writer, index=False)
      writer.save()
      print("Columna creada correctamente.")
    else:
      print("La columna ingresada se encuentra repetida.")
  elif op == 6:
    print(df.head())
  elif op == 7:
    break
  else:
    print("La opción ingresada no es correcta.")